// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

// One answer in the questionnaire.
// - Either `answerId` or `answerText` must be provided.
type QuestionnaireAnswer struct {
	// Question identifier.
	QuestionID string `json:"questionId"`
	// Chosen option ID, if the question is multiple-choice.
	AnswerID *string `json:"answerId,omitempty"`
	// Free-text answer, if applicable.
	AnswerText *string `json:"answerText,omitempty"`
}

// Input counterpart for questionnaire answers.
// - Either `answerId` or `answerText` is required.
type QuestionnaireAnswerInput struct {
	QuestionID string  `json:"questionId" validate:"required"`
	AnswerID   *string `json:"answerId,omitempty" validate:"required_without=AnswerText,excluded_with=AnswerText"`
	AnswerText *string `json:"answerText,omitempty" validate:"required_without=AnswerID,excluded_with=AnswerID"`
}

// Input for user registration.
type RegisterUserInput struct {
	Email                string                      `json:"email" validate:"required,email"`
	Password             string                      `json:"password" validate:"required,min=8"`
	ConfirmPassword      string                      `json:"confirmPassword" validate:"eqfield=Password"`
	Age                  *int                        `json:"age,omitempty" validate:"omitempty,gte=18" message:"Age must be 18+ or left blank"`
	TermsAndConditions   []string                    `json:"termsAndConditions" validate:"required,min=1"`
	QuestionnaireAnswers []*QuestionnaireAnswerInput `json:"questionnaireAnswers,omitempty" validate:"required,min=1,dive"`
}

// A user in the system.
type User struct {
	// Unique identifier.
	ID string `json:"id"`
	// Primary email address.
	Email string `json:"email"`
	// Age in years (optional).
	Age *int `json:"age,omitempty"`
	// Hashed password or placeholder (avoid returning this to clients).
	Password string `json:"password"`
	// IDs of accepted Terms & Conditions versions.
	// At least one must be accepted during registration.
	TermsAndConditions []string `json:"termsAndConditions"`
	// Answers provided to the onboarding questionnaire.
	QuestionnaireAnswers []*QuestionnaireAnswer `json:"questionnaireAnswers"`
}
